version: '3.8'

services:
  slashviberepo:
    build: .
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_ADDR=${REDIS_ADDR:-host.docker.internal:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-slack-commands}
      - REDIS_VIEW_SUBMISSION_CHANNEL=${REDIS_VIEW_SUBMISSION_CHANNEL:-slack-relay-view-submission}
      - REDIS_POPPIT_LIST=${REDIS_POPPIT_LIST:-poppit:notifications}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - GITHUB_ORG=${GITHUB_ORG}
      - WORKING_DIR=${WORKING_DIR:-/tmp}
    restart: unless-stopped
